In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

In [2]:
import requests 

docs_url = 'https://github.com/alexeygrigorev/llm-rag-workshop/raw/main/notebooks/documents.json'
docs_response = requests.get(docs_url)
documents_raw = docs_response.json()

documents = []

for course in documents_raw:
    course_name = course['course']

    for doc in course['documents']:
        doc['course'] = course_name
        documents.append(doc)

In [3]:
df = pd.DataFrame(documents, columns=['course', 'section', 'question', 'text'])

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv = TfidfVectorizer(stop_words='english', min_df=5)
X = cv.fit_transform(df.text)

names = cv.get_feature_names_out()

df_docs = pd.DataFrame(X.toarray(), columns=names).T
df_docs.round(0)

0    1    2    3    4    5    6    7    8    9    ...  938  939  \
01        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
02        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
03        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
04        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
05        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
yes       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
yml       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
youtube   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
zip       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
zoomcamp  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   

          940  941  942  943  944  945  946  947  
01        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
02        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
03        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
04        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
05        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...       ...  ...  ...  ...  ...  ...  ...  ...  
yes       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
yml       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
youtube   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
zip       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
zoomcamp  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[1333 rows x 948 columns]

In [5]:
fields = ['section','question','text']
matrices = {}
vectorizers = {}

for f in fields:
    cv = TfidfVectorizer(stop_words='english', min_df=5)
    X = cv.fit_transform(df[f])
    matrices[f] = X
    vectorizers[f] =cv
    

In [6]:
X # we can compress de matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 23808 stored elements and shape (948, 1333)>

LATENT SEMANTIC ANALYSIS (LSA)

In [7]:
from sklearn.decomposition import TruncatedSVD # for taking care of synonyms

X = matrices['text']
cv = vectorizers['text']

svd = TruncatedSVD(n_components=16)
X_emb = svd.fit_transform(X)

X_emb[0]

array([ 0.09653674, -0.08208706, -0.10282845, -0.07843821,  0.06808244,
       -0.06090695,  0.01894535, -0.11304847,  0.25863085,  0.28055791,
        0.0777681 ,  0.03984445, -0.1158799 ,  0.07846779, -0.02760938,
       -0.0439627 ])

In [8]:
X_emb.shape #16 rows instead of 1333 before

(948, 16)

In [9]:
query = 'I just singned up. Is it too late to join the course?'

Q = cv.transform([query])
Q_emb = svd.transform(Q)
Q_emb[0]

array([ 0.0579051 , -0.03850996, -0.05694751, -0.02783495,  0.04022132,
       -0.0610254 ,  0.00888581, -0.07349992,  0.17855228,  0.18095004,
        0.0587173 ,  0.04855778, -0.07364841,  0.05203681, -0.03771937,
       -0.04679333])

In [10]:
np.dot(X_emb[0], Q_emb[0]) #cosine similarity

np.float64(0.15088626058888405)

In [11]:
score = cosine_similarity(X_emb, Q_emb).flatten()
idx = np.argsort(-score)[:10]
list(df.loc[idx].text)

["The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
 'If you have submitted two projects (and peer-reviewed at least 3 course-mates’ projects for each submission), you will get the certificate for the course. According to the course coordinator, Alexey Grigorev, only two projects are needed to get the course certificate.\n(optional) David Odimegwu',
 'Yes, you can. You won’t be able to submit some of the homeworks, but you can still take part in the course.\nIn order to get a certificate, you need to submit 2 out of 3 course projects and review 3 peers’ Projects by the deadlin

Non-Negative Matrix Factorization

non-negative inpute matrices produces non negative resultas

In [12]:
from sklearn.decomposition import NMF

nmf = NMF(n_components=16)
X_emb = nmf.fit_transform(X)
X_emb[0]

array([0.00588779, 0.00588256, 0.        , 0.        , 0.08510457,
       0.        , 0.00105174, 0.        , 0.00222891, 0.01231298,
       0.00025929, 0.        , 0.        , 0.00407595, 0.00782517,
       0.00935232])

In [13]:
Q = cv.transform([query])
Q_emb = nmf.transform(Q)
Q_emb[0]

array([0.00686662, 0.00589974, 0.        , 0.00349358, 0.04021438,
       0.        , 0.        , 0.        , 0.00010269, 0.00088296,
       0.        , 0.        , 0.        , 0.00904164, 0.00934204,
       0.        ])

In [14]:
score = cosine_similarity(X_emb, Q_emb).flatten()
idx = np.argsort(-score)[:10]
list(df.loc[idx].text)

['When you post about what you learned from the course on your social media pages, use the tag #mlzoomcamp. When you submit your homework, there’s a section in the form for putting the links there. Separate multiple links by any whitespace character (linebreak, space, tab, etc).\nFor posting the learning in public links, you get extra scores. But the number of scores is limited to 7 points: if you put more than 7 links in your homework form, you’ll get only 7 points.\nThe same content can be posted to 7 different social sites and still earn you 7 points if you add 7 URLs per week, see Alexey’s reply. (~ ellacharmed)\nFor midterms/capstones, the awarded points are doubled as the duration is longer. So for projects the points are capped at 14 for 14 URLs.',
 "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course 

BERT

In [4]:
import torch

from transformers import BertModel, BertTokenizer

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertModel.from_pretrained("bert-base-uncased")
model.eval()  # Set the model to evaluation mode if not training

OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\andre\Documents\LLM_ZOOM\llm-zoomcamp\openai-env\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

In [ ]:
texts = [
    "Yes, we will keep all the materials after the course finishes.",
    "You can follow the course at your own pace after it finishes"
]
encoded_input = tokenizer(texts, padding=True, truncation=True, return_tensors='pt')

In [ ]:
with torch.no_grad():  # Disable gradient calculation for inference
    outputs = model(**encoded_input)
    hidden_states = outputs.last_hidden_state